[table]
name = "bulletin"
comment = "游戏公告"

[[column]]
name = "id"
primary_key = true
type = "int"
length = 11
unsigned = true
not_null = true
auto_increment = true
comment = "主键ID"

[[column]]
name = "title"
type = "varchar"
length = 200
not_null = true
comment = "标题"

[[column]]
name = "content"
type = "varchar"
length = 8000
not_null = true
comment = "内容"

[[column]]
name = "targets"
type = "json"
not_null = true
comment = "平台渠道范围"
java_type = "List<gm.business.entity.req.PlatformTarget>"

[[column]]
name = "begintime"
type = "datetime"
not_null = true

[[column]]
name = "endtime"
type = "datetime"
not_null = true

[[column]]
name = "weight"
type = "int"
not_null = true
default = 0

[[column]]
name = "is_new"
type = "int"
not_null = true
comment = "是否新项"
default = 0
set = [[0, 1], ["否", "是"]]

[[column]]
name = "duration"
type = "int"
not_null = true
comment = "间隔时间，单位：分钟"
default = 0

[[column]]
name = "state"
type = "int"
not_null = true
comment = "在线状态"
default = 0
set = [[0, 1, 2], ["待上线", "在线中", "已下线"]]

[[column]]
name = "cretaed_by"
type = "varchar"
length = 45
not_null = true
comment = "创建人"

[[column]]
name = "updated_by"
type = "varchar"
length = 45
not_null = true
comment = "最后编辑人"

[[column]]
name = "created_at"
type = "datetime"
not_null = true
comment = "创建时间"
default = "CURRENT_TIMESTAMP"

[[column]]
name = "updated_at"
type = "datetime"
not_null = true
comment = "最后更新时间"
default = "CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP"

