[table]
name = "bulletin"
comment = "游戏公告"

[[column]]
name = "id"
primary_key = true
db_type = "int"
length = 11
unsigned = true
not_null = true
auto_increment = true
comment = "主键ID"

[[column]]
name = "bulletin_category_id"
ref_table="bulletin_category"
db_type = "int"
length = 11
unsigned = true
not_null = true
comment = "公告类型"

[[column]]
name = "title"
db_type = "varchar"
length = 200
not_null = true
comment = "标题"

[[column]]
name = "content"
db_type = "varchar"
length = 8000
not_null = true
comment = "内容"

[[column]]
name = "targets"
db_type = "json"
not_null = true
comment = "平台渠道范围"
java_type = "List<gm.business.entity.req.PlatformTarget>"

[[column]]
name = "begintime"
db_type = "datetime"
comment = "上线时间"
not_null = true

[[column]]
name = "endtime"
db_type = "datetime"
comment = "预计下线时间"
not_null = true

[[column]]
name = "weight"
db_type = "int"
comment = "权重：值越大越靠前"
not_null = true
default = '0'

[[column]]
name = "is_new"
db_type = "int"
not_null = true
comment = "是否新项"
default = '0'
set = [[0, 1], ["否", "是"]]

[[column]]
name = "duration"
db_type = "int"
not_null = true
comment = "间隔时间（分钟）"
default = '0'

[[column]]
name = "state"
db_type = "int"
not_null = true
comment = "在线状态"
default = '0'
set = [[0, 1, 2], ["待上线", "在线中", "已下线"]]

[[column]]
name = "created_by"
db_type = "varchar"
length = 45
comment = "创建人"

[[column]]
name = "updated_by"
db_type = "varchar"
length = 45
comment = "最后编辑人"

[[column]]
name = "created_at"
db_type = "datetime"
comment = "创建时间"
default = "CURRENT_TIMESTAMP"

[[column]]
name = "updated_at"
db_type = "datetime"
comment = "最后更新时间"
default = "CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP"

